import {innerTablePropsInterface} from './types'
import styles from '../ui/Table.module.scss'
export const tableDefault: innerTablePropsInterface = {
  id: 'table',
  isLoading: false,
  emptyMessage: 'Полей нет',
  fields: [
    { name: 'Поле 1', styles: {width: '100px'}},
    { name: 'Поле 3'}
  ],

  classNames: {
    table:{name:styles.table, useDefault:true},
    head: {name: styles.table__head, useDefault: true},
    headRow: {name: styles["table__head-row"], useDefault: true},
    headCell: {name: styles["table__head-cell"], useDefault: true},
    headCellText: {name: styles["table__head-cell-text"], useDefault: true},
    body: {name: styles.table__body, useDefault: true},
    row: {name: styles.table__row, useDefault: true},
    cell: {name: styles.table__cell, useDefault: true},
    loader: {name: styles.table__loader, useDefault: true},
    cellText: {name: styles["table__cell-text"], useDefault: true},
    select: {name: styles.table__select, useDefault: true},
    selectSquare: {name: styles['table__select-square'], useDefault: true},
    selectCheckMark: {name: styles["table__select-check-mark"], useDefault: true},
    expansionRow: {name: styles["table__expansion-row"], useDefault: true},
    expansionArrow: {name: styles["table__expansion-arrow"], useDefault: true},
    expansionArrowActive: {name: styles["table__expansion-arrow--active"], useDefault: true},
    expansionElement: {name: styles["table__expansion-element"], useDefault: true},
    headerSpansRow: {name: styles['table__header-spans__row'], useDefault: true},
    headerSpansCell: {name: styles['table__header-spans__cell'], useDefault: true},
    headerSpansFields: {name: styles['table__header-spans__fields'], useDefault: true},
    delete:{name:styles.table__delete, useDefault:true},
    deleteMark:{name:styles["table__delete-mark"], useDefault:true},
    paginationArrow: {name: styles["table__pagination__arrow"], useDefault:true},
    paginationArrowLeft: {name: styles["table__pagination__arrow--left"], useDefault:true},
    paginationArrowRight: {name: styles["table__pagination__arrow--right"], useDefault:true},
    paginationWrapper: {name: styles["table__pagination__wrapper"], useDefault:true},
    pagination: {name: styles["table__pagination"], useDefault:true},
  },
  selectColNum: 0,
  countRowForFetch: 10,
  selectedAll:false,
  showHeaders: true,
  headerSpans:[],
  changedRowIndex: null,
  expansionRowsIndexes: [],
  canDelete:false,
  canDragRecords: false,
  canDropRecords: false,
  autoFetch: true,
  recordsPerPage: 15,
  page: 0,
  currentX: 0
}
