// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'data_item': string;
  'data_profile': string;
  'mailIcon_icon': string;
  'sideBarContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
