// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'slider__arrow': string;
  'slider__arrow--left': string;
  'slider__arrow--right': string;
  'slider__pagination__dot': string;
  'slider__pagination__dot--active': string;
  'slider__pagination__wrapper': string;
  'slider__wrapper': string;
  'slider__wrapper__inner': string;
  'slider__wrapper__overflow': string;
}
export const cssExports: CssExports;
export default cssExports;
