// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'spin': string;
  'table': string;
  'table__body': string;
  'table__cell': string;
  'table__cell-text': string;
  'table__delete': string;
  'table__delete-mark': string;
  'table__expansion-arrow': string;
  'table__expansion-arrow--active': string;
  'table__expansion-element': string;
  'table__expansion-row': string;
  'table__head': string;
  'table__head-cell': string;
  'table__head-cell-text': string;
  'table__head-row': string;
  'table__header-spans__cell': string;
  'table__header-spans__fields': string;
  'table__header-spans__row': string;
  'table__loader': string;
  'table__row': string;
  'table__select': string;
  'table__select-check-mark': string;
  'table__select-enter': string;
  'table__select-enter-active': string;
  'table__select-exit': string;
  'table__select-exit-active': string;
  'table__select-square': string;
  'table__treeGrid-border': string;
  'table__treeGrid-button': string;
  'table__treeGrid-button--active': string;
}
export const cssExports: CssExports;
export default cssExports;
