// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inputFile': string;
  'inputFile__label': string;
  'inputFile__label--active': string;
  'inputFile__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
